In [26]:
import numpy as np

In [27]:
x=np.array([1,2,3,4,5,6,7,8,9])
print(x[0:5])

[1 2 3 4 5]


In [28]:
x=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(x[0,0:3])
print(x[1,0:3])

[1 2 3]
[6 7 8]


In [29]:
x=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(x.shape)
print(x)
y=x.reshape(-1)
print(y)

(2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


In [30]:
for a in x:
    print(a)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [32]:
z=x.copy()
print(z)
c=x.view()
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [36]:
x=np.ones((3,3),dtype="i")
print(x)
x=np.full((3,3),13)
print(x)
 

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[13 13 13]
 [13 13 13]
 [13 13 13]]
